
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class BTP
{

    public string MaBTP { get; set; }

    public byte[] HaBTP { get; set; }

    public string TenBTP { get; set; }

    public string MaDV { get; set; }

    public string MaKho { get; set; }

    public string MaCP { get; set; }

    public string Mota { get; set; }

}

}
