
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Dongia
{

    public string MaDG { get; set; }

    public string MaSP { get; set; }

    public string TenSP { get; set; }

    public string MaDV { get; set; }

    public decimal Gia { get; set; }

    public string Note { get; set; }

}

}
