
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class MQC
{

    public string MaQC { get; set; }

    public string MaVL { get; set; }

    public string MaBTP { get; set; }

    public string MaTP { get; set; }

    public string TenQC { get; set; }

    public Nullable<short> Giamua { get; set; }

    public Nullable<short> Giaban { get; set; }

    public Nullable<short> Dongia { get; set; }

    public string Note { get; set; }

}

}
