
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Nhanvien
{

    public string MaNV { get; set; }

    public string MaCV { get; set; }

    public byte[] HaNV { get; set; }

    public string TenNV { get; set; }

    public bool Sex { get; set; }

    public Nullable<short> SDT { get; set; }

    public string Address { get; set; }

    public Nullable<short> CCCD { get; set; }

    public Nullable<System.DateTime> ByDate { get; set; }

    public Nullable<System.DateTime> CreatDtae { get; set; }

}

}
