
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class NVL
{

    public string MaVL { get; set; }

    public byte[] HaVL { get; set; }

    public string TenVL { get; set; }

    public string MaDV { get; set; }

    public string Makho { get; set; }

    public string MaCP { get; set; }

    public string Note { get; set; }

}

}
