
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Quydoi
{

    public string MaQD { get; set; }

    public string MaVL { get; set; }

    public string MaQC { get; set; }

    public string TenQD { get; set; }

    public string MaDVQD { get; set; }

    public string MaDVC { get; set; }

    public short Tyle { get; set; }

    public string Note { get; set; }

}

}
