
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class THSPTN
{

    public string MaTHSPTN { get; set; }

    public Nullable<short> Date { get; set; }

    public string MaTo { get; set; }

    public string MaKho { get; set; }

    public string MaVL { get; set; }

    public string MaBTP { get; set; }

    public string MaTP { get; set; }

    public string MaDV { get; set; }

    public string MaNV { get; set; }

    public short SL { get; set; }

    public string MaDG { get; set; }

    public decimal Tien { get; set; }

    public string Note { get; set; }

}

}
