
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Tonkho
{

    public string MaTKho { get; set; }

    public string MaVL { get; set; }

    public string MaBTP { get; set; }

    public Nullable<decimal> MaTP { get; set; }

    public string MaDV { get; set; }

    public short SL { get; set; }

    public string Note { get; set; }

}

}
