
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class TP
{

    public string MaTP { get; set; }

    public byte[] HaTP { get; set; }

    public string TenTP { get; set; }

    public decimal MaDV { get; set; }

    public string MaKho { get; set; }

    public string MaDthu { get; set; }

    public string Note { get; set; }

}

}
