
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tín_Phát_Metech.EF
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public string MaTK { get; set; }

    public string MaNV { get; set; }

    public string TK { get; set; }

    public string MK { get; set; }

    public string Quyen { get; set; }

    public System.DateTime CreatDate { get; set; }

}

}
